// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/cni-wrapper-plugin/netrules"
	"code.cloudfoundry.org/lib/rules"
)

type RuleConverter struct {
	BulkConvertStub        func([]netrules.Rule, string, bool) []rules.IPTablesRule
	bulkConvertMutex       sync.RWMutex
	bulkConvertArgsForCall []struct {
		arg1 []netrules.Rule
		arg2 string
		arg3 bool
	}
	bulkConvertReturns struct {
		result1 []rules.IPTablesRule
	}
	bulkConvertReturnsOnCall map[int]struct {
		result1 []rules.IPTablesRule
	}
	ConvertStub        func(netrules.Rule, string, bool) []rules.IPTablesRule
	convertMutex       sync.RWMutex
	convertArgsForCall []struct {
		arg1 netrules.Rule
		arg2 string
		arg3 bool
	}
	convertReturns struct {
		result1 []rules.IPTablesRule
	}
	convertReturnsOnCall map[int]struct {
		result1 []rules.IPTablesRule
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *RuleConverter) BulkConvert(arg1 []netrules.Rule, arg2 string, arg3 bool) []rules.IPTablesRule {
	var arg1Copy []netrules.Rule
	if arg1 != nil {
		arg1Copy = make([]netrules.Rule, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.bulkConvertMutex.Lock()
	ret, specificReturn := fake.bulkConvertReturnsOnCall[len(fake.bulkConvertArgsForCall)]
	fake.bulkConvertArgsForCall = append(fake.bulkConvertArgsForCall, struct {
		arg1 []netrules.Rule
		arg2 string
		arg3 bool
	}{arg1Copy, arg2, arg3})
	stub := fake.BulkConvertStub
	fakeReturns := fake.bulkConvertReturns
	fake.recordInvocation("BulkConvert", []interface{}{arg1Copy, arg2, arg3})
	fake.bulkConvertMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RuleConverter) BulkConvertCallCount() int {
	fake.bulkConvertMutex.RLock()
	defer fake.bulkConvertMutex.RUnlock()
	return len(fake.bulkConvertArgsForCall)
}

func (fake *RuleConverter) BulkConvertCalls(stub func([]netrules.Rule, string, bool) []rules.IPTablesRule) {
	fake.bulkConvertMutex.Lock()
	defer fake.bulkConvertMutex.Unlock()
	fake.BulkConvertStub = stub
}

func (fake *RuleConverter) BulkConvertArgsForCall(i int) ([]netrules.Rule, string, bool) {
	fake.bulkConvertMutex.RLock()
	defer fake.bulkConvertMutex.RUnlock()
	argsForCall := fake.bulkConvertArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *RuleConverter) BulkConvertReturns(result1 []rules.IPTablesRule) {
	fake.bulkConvertMutex.Lock()
	defer fake.bulkConvertMutex.Unlock()
	fake.BulkConvertStub = nil
	fake.bulkConvertReturns = struct {
		result1 []rules.IPTablesRule
	}{result1}
}

func (fake *RuleConverter) BulkConvertReturnsOnCall(i int, result1 []rules.IPTablesRule) {
	fake.bulkConvertMutex.Lock()
	defer fake.bulkConvertMutex.Unlock()
	fake.BulkConvertStub = nil
	if fake.bulkConvertReturnsOnCall == nil {
		fake.bulkConvertReturnsOnCall = make(map[int]struct {
			result1 []rules.IPTablesRule
		})
	}
	fake.bulkConvertReturnsOnCall[i] = struct {
		result1 []rules.IPTablesRule
	}{result1}
}

func (fake *RuleConverter) Convert(arg1 netrules.Rule, arg2 string, arg3 bool) []rules.IPTablesRule {
	fake.convertMutex.Lock()
	ret, specificReturn := fake.convertReturnsOnCall[len(fake.convertArgsForCall)]
	fake.convertArgsForCall = append(fake.convertArgsForCall, struct {
		arg1 netrules.Rule
		arg2 string
		arg3 bool
	}{arg1, arg2, arg3})
	stub := fake.ConvertStub
	fakeReturns := fake.convertReturns
	fake.recordInvocation("Convert", []interface{}{arg1, arg2, arg3})
	fake.convertMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RuleConverter) ConvertCallCount() int {
	fake.convertMutex.RLock()
	defer fake.convertMutex.RUnlock()
	return len(fake.convertArgsForCall)
}

func (fake *RuleConverter) ConvertCalls(stub func(netrules.Rule, string, bool) []rules.IPTablesRule) {
	fake.convertMutex.Lock()
	defer fake.convertMutex.Unlock()
	fake.ConvertStub = stub
}

func (fake *RuleConverter) ConvertArgsForCall(i int) (netrules.Rule, string, bool) {
	fake.convertMutex.RLock()
	defer fake.convertMutex.RUnlock()
	argsForCall := fake.convertArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *RuleConverter) ConvertReturns(result1 []rules.IPTablesRule) {
	fake.convertMutex.Lock()
	defer fake.convertMutex.Unlock()
	fake.ConvertStub = nil
	fake.convertReturns = struct {
		result1 []rules.IPTablesRule
	}{result1}
}

func (fake *RuleConverter) ConvertReturnsOnCall(i int, result1 []rules.IPTablesRule) {
	fake.convertMutex.Lock()
	defer fake.convertMutex.Unlock()
	fake.ConvertStub = nil
	if fake.convertReturnsOnCall == nil {
		fake.convertReturnsOnCall = make(map[int]struct {
			result1 []rules.IPTablesRule
		})
	}
	fake.convertReturnsOnCall[i] = struct {
		result1 []rules.IPTablesRule
	}{result1}
}

func (fake *RuleConverter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.bulkConvertMutex.RLock()
	defer fake.bulkConvertMutex.RUnlock()
	fake.convertMutex.RLock()
	defer fake.convertMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *RuleConverter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
