// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/vishvananda/netlink"
)

type NetlinkAdapter struct {
	AddrListStub        func(netlink.Link, int) ([]netlink.Addr, error)
	addrListMutex       sync.RWMutex
	addrListArgsForCall []struct {
		arg1 netlink.Link
		arg2 int
	}
	addrListReturns struct {
		result1 []netlink.Addr
		result2 error
	}
	addrListReturnsOnCall map[int]struct {
		result1 []netlink.Addr
		result2 error
	}
	LinkListStub        func() ([]netlink.Link, error)
	linkListMutex       sync.RWMutex
	linkListArgsForCall []struct {
	}
	linkListReturns struct {
		result1 []netlink.Link
		result2 error
	}
	linkListReturnsOnCall map[int]struct {
		result1 []netlink.Link
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *NetlinkAdapter) AddrList(arg1 netlink.Link, arg2 int) ([]netlink.Addr, error) {
	fake.addrListMutex.Lock()
	ret, specificReturn := fake.addrListReturnsOnCall[len(fake.addrListArgsForCall)]
	fake.addrListArgsForCall = append(fake.addrListArgsForCall, struct {
		arg1 netlink.Link
		arg2 int
	}{arg1, arg2})
	stub := fake.AddrListStub
	fakeReturns := fake.addrListReturns
	fake.recordInvocation("AddrList", []interface{}{arg1, arg2})
	fake.addrListMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *NetlinkAdapter) AddrListCallCount() int {
	fake.addrListMutex.RLock()
	defer fake.addrListMutex.RUnlock()
	return len(fake.addrListArgsForCall)
}

func (fake *NetlinkAdapter) AddrListCalls(stub func(netlink.Link, int) ([]netlink.Addr, error)) {
	fake.addrListMutex.Lock()
	defer fake.addrListMutex.Unlock()
	fake.AddrListStub = stub
}

func (fake *NetlinkAdapter) AddrListArgsForCall(i int) (netlink.Link, int) {
	fake.addrListMutex.RLock()
	defer fake.addrListMutex.RUnlock()
	argsForCall := fake.addrListArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *NetlinkAdapter) AddrListReturns(result1 []netlink.Addr, result2 error) {
	fake.addrListMutex.Lock()
	defer fake.addrListMutex.Unlock()
	fake.AddrListStub = nil
	fake.addrListReturns = struct {
		result1 []netlink.Addr
		result2 error
	}{result1, result2}
}

func (fake *NetlinkAdapter) AddrListReturnsOnCall(i int, result1 []netlink.Addr, result2 error) {
	fake.addrListMutex.Lock()
	defer fake.addrListMutex.Unlock()
	fake.AddrListStub = nil
	if fake.addrListReturnsOnCall == nil {
		fake.addrListReturnsOnCall = make(map[int]struct {
			result1 []netlink.Addr
			result2 error
		})
	}
	fake.addrListReturnsOnCall[i] = struct {
		result1 []netlink.Addr
		result2 error
	}{result1, result2}
}

func (fake *NetlinkAdapter) LinkList() ([]netlink.Link, error) {
	fake.linkListMutex.Lock()
	ret, specificReturn := fake.linkListReturnsOnCall[len(fake.linkListArgsForCall)]
	fake.linkListArgsForCall = append(fake.linkListArgsForCall, struct {
	}{})
	stub := fake.LinkListStub
	fakeReturns := fake.linkListReturns
	fake.recordInvocation("LinkList", []interface{}{})
	fake.linkListMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *NetlinkAdapter) LinkListCallCount() int {
	fake.linkListMutex.RLock()
	defer fake.linkListMutex.RUnlock()
	return len(fake.linkListArgsForCall)
}

func (fake *NetlinkAdapter) LinkListCalls(stub func() ([]netlink.Link, error)) {
	fake.linkListMutex.Lock()
	defer fake.linkListMutex.Unlock()
	fake.LinkListStub = stub
}

func (fake *NetlinkAdapter) LinkListReturns(result1 []netlink.Link, result2 error) {
	fake.linkListMutex.Lock()
	defer fake.linkListMutex.Unlock()
	fake.LinkListStub = nil
	fake.linkListReturns = struct {
		result1 []netlink.Link
		result2 error
	}{result1, result2}
}

func (fake *NetlinkAdapter) LinkListReturnsOnCall(i int, result1 []netlink.Link, result2 error) {
	fake.linkListMutex.Lock()
	defer fake.linkListMutex.Unlock()
	fake.LinkListStub = nil
	if fake.linkListReturnsOnCall == nil {
		fake.linkListReturnsOnCall = make(map[int]struct {
			result1 []netlink.Link
			result2 error
		})
	}
	fake.linkListReturnsOnCall[i] = struct {
		result1 []netlink.Link
		result2 error
	}{result1, result2}
}

func (fake *NetlinkAdapter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addrListMutex.RLock()
	defer fake.addrListMutex.RUnlock()
	fake.linkListMutex.RLock()
	defer fake.linkListMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *NetlinkAdapter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
