// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"
)

type CIDRPool struct {
	GetAvailableBlockStub        func([]string) string
	getAvailableBlockMutex       sync.RWMutex
	getAvailableBlockArgsForCall []struct {
		arg1 []string
	}
	getAvailableBlockReturns struct {
		result1 string
	}
	getAvailableBlockReturnsOnCall map[int]struct {
		result1 string
	}
	GetAvailableSingleIPStub        func([]string) string
	getAvailableSingleIPMutex       sync.RWMutex
	getAvailableSingleIPArgsForCall []struct {
		arg1 []string
	}
	getAvailableSingleIPReturns struct {
		result1 string
	}
	getAvailableSingleIPReturnsOnCall map[int]struct {
		result1 string
	}
	IsMemberStub        func(string) bool
	isMemberMutex       sync.RWMutex
	isMemberArgsForCall []struct {
		arg1 string
	}
	isMemberReturns struct {
		result1 bool
	}
	isMemberReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CIDRPool) GetAvailableBlock(arg1 []string) string {
	var arg1Copy []string
	if arg1 != nil {
		arg1Copy = make([]string, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.getAvailableBlockMutex.Lock()
	ret, specificReturn := fake.getAvailableBlockReturnsOnCall[len(fake.getAvailableBlockArgsForCall)]
	fake.getAvailableBlockArgsForCall = append(fake.getAvailableBlockArgsForCall, struct {
		arg1 []string
	}{arg1Copy})
	stub := fake.GetAvailableBlockStub
	fakeReturns := fake.getAvailableBlockReturns
	fake.recordInvocation("GetAvailableBlock", []interface{}{arg1Copy})
	fake.getAvailableBlockMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CIDRPool) GetAvailableBlockCallCount() int {
	fake.getAvailableBlockMutex.RLock()
	defer fake.getAvailableBlockMutex.RUnlock()
	return len(fake.getAvailableBlockArgsForCall)
}

func (fake *CIDRPool) GetAvailableBlockCalls(stub func([]string) string) {
	fake.getAvailableBlockMutex.Lock()
	defer fake.getAvailableBlockMutex.Unlock()
	fake.GetAvailableBlockStub = stub
}

func (fake *CIDRPool) GetAvailableBlockArgsForCall(i int) []string {
	fake.getAvailableBlockMutex.RLock()
	defer fake.getAvailableBlockMutex.RUnlock()
	argsForCall := fake.getAvailableBlockArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CIDRPool) GetAvailableBlockReturns(result1 string) {
	fake.getAvailableBlockMutex.Lock()
	defer fake.getAvailableBlockMutex.Unlock()
	fake.GetAvailableBlockStub = nil
	fake.getAvailableBlockReturns = struct {
		result1 string
	}{result1}
}

func (fake *CIDRPool) GetAvailableBlockReturnsOnCall(i int, result1 string) {
	fake.getAvailableBlockMutex.Lock()
	defer fake.getAvailableBlockMutex.Unlock()
	fake.GetAvailableBlockStub = nil
	if fake.getAvailableBlockReturnsOnCall == nil {
		fake.getAvailableBlockReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getAvailableBlockReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *CIDRPool) GetAvailableSingleIP(arg1 []string) string {
	var arg1Copy []string
	if arg1 != nil {
		arg1Copy = make([]string, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.getAvailableSingleIPMutex.Lock()
	ret, specificReturn := fake.getAvailableSingleIPReturnsOnCall[len(fake.getAvailableSingleIPArgsForCall)]
	fake.getAvailableSingleIPArgsForCall = append(fake.getAvailableSingleIPArgsForCall, struct {
		arg1 []string
	}{arg1Copy})
	stub := fake.GetAvailableSingleIPStub
	fakeReturns := fake.getAvailableSingleIPReturns
	fake.recordInvocation("GetAvailableSingleIP", []interface{}{arg1Copy})
	fake.getAvailableSingleIPMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CIDRPool) GetAvailableSingleIPCallCount() int {
	fake.getAvailableSingleIPMutex.RLock()
	defer fake.getAvailableSingleIPMutex.RUnlock()
	return len(fake.getAvailableSingleIPArgsForCall)
}

func (fake *CIDRPool) GetAvailableSingleIPCalls(stub func([]string) string) {
	fake.getAvailableSingleIPMutex.Lock()
	defer fake.getAvailableSingleIPMutex.Unlock()
	fake.GetAvailableSingleIPStub = stub
}

func (fake *CIDRPool) GetAvailableSingleIPArgsForCall(i int) []string {
	fake.getAvailableSingleIPMutex.RLock()
	defer fake.getAvailableSingleIPMutex.RUnlock()
	argsForCall := fake.getAvailableSingleIPArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CIDRPool) GetAvailableSingleIPReturns(result1 string) {
	fake.getAvailableSingleIPMutex.Lock()
	defer fake.getAvailableSingleIPMutex.Unlock()
	fake.GetAvailableSingleIPStub = nil
	fake.getAvailableSingleIPReturns = struct {
		result1 string
	}{result1}
}

func (fake *CIDRPool) GetAvailableSingleIPReturnsOnCall(i int, result1 string) {
	fake.getAvailableSingleIPMutex.Lock()
	defer fake.getAvailableSingleIPMutex.Unlock()
	fake.GetAvailableSingleIPStub = nil
	if fake.getAvailableSingleIPReturnsOnCall == nil {
		fake.getAvailableSingleIPReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getAvailableSingleIPReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *CIDRPool) IsMember(arg1 string) bool {
	fake.isMemberMutex.Lock()
	ret, specificReturn := fake.isMemberReturnsOnCall[len(fake.isMemberArgsForCall)]
	fake.isMemberArgsForCall = append(fake.isMemberArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IsMemberStub
	fakeReturns := fake.isMemberReturns
	fake.recordInvocation("IsMember", []interface{}{arg1})
	fake.isMemberMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CIDRPool) IsMemberCallCount() int {
	fake.isMemberMutex.RLock()
	defer fake.isMemberMutex.RUnlock()
	return len(fake.isMemberArgsForCall)
}

func (fake *CIDRPool) IsMemberCalls(stub func(string) bool) {
	fake.isMemberMutex.Lock()
	defer fake.isMemberMutex.Unlock()
	fake.IsMemberStub = stub
}

func (fake *CIDRPool) IsMemberArgsForCall(i int) string {
	fake.isMemberMutex.RLock()
	defer fake.isMemberMutex.RUnlock()
	argsForCall := fake.isMemberArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CIDRPool) IsMemberReturns(result1 bool) {
	fake.isMemberMutex.Lock()
	defer fake.isMemberMutex.Unlock()
	fake.IsMemberStub = nil
	fake.isMemberReturns = struct {
		result1 bool
	}{result1}
}

func (fake *CIDRPool) IsMemberReturnsOnCall(i int, result1 bool) {
	fake.isMemberMutex.Lock()
	defer fake.isMemberMutex.Unlock()
	fake.IsMemberStub = nil
	if fake.isMemberReturnsOnCall == nil {
		fake.isMemberReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isMemberReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *CIDRPool) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAvailableBlockMutex.RLock()
	defer fake.getAvailableBlockMutex.RUnlock()
	fake.getAvailableSingleIPMutex.RLock()
	defer fake.getAvailableSingleIPMutex.RUnlock()
	fake.isMemberMutex.RLock()
	defer fake.isMemberMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CIDRPool) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
