// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"net"
	"sync"
)

type HardwareAddressGenerator struct {
	GenerateForVTEPStub        func(net.IP) (net.HardwareAddr, error)
	generateForVTEPMutex       sync.RWMutex
	generateForVTEPArgsForCall []struct {
		arg1 net.IP
	}
	generateForVTEPReturns struct {
		result1 net.HardwareAddr
		result2 error
	}
	generateForVTEPReturnsOnCall map[int]struct {
		result1 net.HardwareAddr
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *HardwareAddressGenerator) GenerateForVTEP(arg1 net.IP) (net.HardwareAddr, error) {
	fake.generateForVTEPMutex.Lock()
	ret, specificReturn := fake.generateForVTEPReturnsOnCall[len(fake.generateForVTEPArgsForCall)]
	fake.generateForVTEPArgsForCall = append(fake.generateForVTEPArgsForCall, struct {
		arg1 net.IP
	}{arg1})
	stub := fake.GenerateForVTEPStub
	fakeReturns := fake.generateForVTEPReturns
	fake.recordInvocation("GenerateForVTEP", []interface{}{arg1})
	fake.generateForVTEPMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *HardwareAddressGenerator) GenerateForVTEPCallCount() int {
	fake.generateForVTEPMutex.RLock()
	defer fake.generateForVTEPMutex.RUnlock()
	return len(fake.generateForVTEPArgsForCall)
}

func (fake *HardwareAddressGenerator) GenerateForVTEPCalls(stub func(net.IP) (net.HardwareAddr, error)) {
	fake.generateForVTEPMutex.Lock()
	defer fake.generateForVTEPMutex.Unlock()
	fake.GenerateForVTEPStub = stub
}

func (fake *HardwareAddressGenerator) GenerateForVTEPArgsForCall(i int) net.IP {
	fake.generateForVTEPMutex.RLock()
	defer fake.generateForVTEPMutex.RUnlock()
	argsForCall := fake.generateForVTEPArgsForCall[i]
	return argsForCall.arg1
}

func (fake *HardwareAddressGenerator) GenerateForVTEPReturns(result1 net.HardwareAddr, result2 error) {
	fake.generateForVTEPMutex.Lock()
	defer fake.generateForVTEPMutex.Unlock()
	fake.GenerateForVTEPStub = nil
	fake.generateForVTEPReturns = struct {
		result1 net.HardwareAddr
		result2 error
	}{result1, result2}
}

func (fake *HardwareAddressGenerator) GenerateForVTEPReturnsOnCall(i int, result1 net.HardwareAddr, result2 error) {
	fake.generateForVTEPMutex.Lock()
	defer fake.generateForVTEPMutex.Unlock()
	fake.GenerateForVTEPStub = nil
	if fake.generateForVTEPReturnsOnCall == nil {
		fake.generateForVTEPReturnsOnCall = make(map[int]struct {
			result1 net.HardwareAddr
			result2 error
		})
	}
	fake.generateForVTEPReturnsOnCall[i] = struct {
		result1 net.HardwareAddr
		result2 error
	}{result1, result2}
}

func (fake *HardwareAddressGenerator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.generateForVTEPMutex.RLock()
	defer fake.generateForVTEPMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *HardwareAddressGenerator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
