// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"net"
	"sync"
)

type NetAdapter struct {
	InterfaceAddrsStub        func(net.Interface) ([]net.Addr, error)
	interfaceAddrsMutex       sync.RWMutex
	interfaceAddrsArgsForCall []struct {
		arg1 net.Interface
	}
	interfaceAddrsReturns struct {
		result1 []net.Addr
		result2 error
	}
	interfaceAddrsReturnsOnCall map[int]struct {
		result1 []net.Addr
		result2 error
	}
	InterfaceByNameStub        func(string) (*net.Interface, error)
	interfaceByNameMutex       sync.RWMutex
	interfaceByNameArgsForCall []struct {
		arg1 string
	}
	interfaceByNameReturns struct {
		result1 *net.Interface
		result2 error
	}
	interfaceByNameReturnsOnCall map[int]struct {
		result1 *net.Interface
		result2 error
	}
	InterfacesStub        func() ([]net.Interface, error)
	interfacesMutex       sync.RWMutex
	interfacesArgsForCall []struct {
	}
	interfacesReturns struct {
		result1 []net.Interface
		result2 error
	}
	interfacesReturnsOnCall map[int]struct {
		result1 []net.Interface
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *NetAdapter) InterfaceAddrs(arg1 net.Interface) ([]net.Addr, error) {
	fake.interfaceAddrsMutex.Lock()
	ret, specificReturn := fake.interfaceAddrsReturnsOnCall[len(fake.interfaceAddrsArgsForCall)]
	fake.interfaceAddrsArgsForCall = append(fake.interfaceAddrsArgsForCall, struct {
		arg1 net.Interface
	}{arg1})
	stub := fake.InterfaceAddrsStub
	fakeReturns := fake.interfaceAddrsReturns
	fake.recordInvocation("InterfaceAddrs", []interface{}{arg1})
	fake.interfaceAddrsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *NetAdapter) InterfaceAddrsCallCount() int {
	fake.interfaceAddrsMutex.RLock()
	defer fake.interfaceAddrsMutex.RUnlock()
	return len(fake.interfaceAddrsArgsForCall)
}

func (fake *NetAdapter) InterfaceAddrsCalls(stub func(net.Interface) ([]net.Addr, error)) {
	fake.interfaceAddrsMutex.Lock()
	defer fake.interfaceAddrsMutex.Unlock()
	fake.InterfaceAddrsStub = stub
}

func (fake *NetAdapter) InterfaceAddrsArgsForCall(i int) net.Interface {
	fake.interfaceAddrsMutex.RLock()
	defer fake.interfaceAddrsMutex.RUnlock()
	argsForCall := fake.interfaceAddrsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *NetAdapter) InterfaceAddrsReturns(result1 []net.Addr, result2 error) {
	fake.interfaceAddrsMutex.Lock()
	defer fake.interfaceAddrsMutex.Unlock()
	fake.InterfaceAddrsStub = nil
	fake.interfaceAddrsReturns = struct {
		result1 []net.Addr
		result2 error
	}{result1, result2}
}

func (fake *NetAdapter) InterfaceAddrsReturnsOnCall(i int, result1 []net.Addr, result2 error) {
	fake.interfaceAddrsMutex.Lock()
	defer fake.interfaceAddrsMutex.Unlock()
	fake.InterfaceAddrsStub = nil
	if fake.interfaceAddrsReturnsOnCall == nil {
		fake.interfaceAddrsReturnsOnCall = make(map[int]struct {
			result1 []net.Addr
			result2 error
		})
	}
	fake.interfaceAddrsReturnsOnCall[i] = struct {
		result1 []net.Addr
		result2 error
	}{result1, result2}
}

func (fake *NetAdapter) InterfaceByName(arg1 string) (*net.Interface, error) {
	fake.interfaceByNameMutex.Lock()
	ret, specificReturn := fake.interfaceByNameReturnsOnCall[len(fake.interfaceByNameArgsForCall)]
	fake.interfaceByNameArgsForCall = append(fake.interfaceByNameArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.InterfaceByNameStub
	fakeReturns := fake.interfaceByNameReturns
	fake.recordInvocation("InterfaceByName", []interface{}{arg1})
	fake.interfaceByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *NetAdapter) InterfaceByNameCallCount() int {
	fake.interfaceByNameMutex.RLock()
	defer fake.interfaceByNameMutex.RUnlock()
	return len(fake.interfaceByNameArgsForCall)
}

func (fake *NetAdapter) InterfaceByNameCalls(stub func(string) (*net.Interface, error)) {
	fake.interfaceByNameMutex.Lock()
	defer fake.interfaceByNameMutex.Unlock()
	fake.InterfaceByNameStub = stub
}

func (fake *NetAdapter) InterfaceByNameArgsForCall(i int) string {
	fake.interfaceByNameMutex.RLock()
	defer fake.interfaceByNameMutex.RUnlock()
	argsForCall := fake.interfaceByNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *NetAdapter) InterfaceByNameReturns(result1 *net.Interface, result2 error) {
	fake.interfaceByNameMutex.Lock()
	defer fake.interfaceByNameMutex.Unlock()
	fake.InterfaceByNameStub = nil
	fake.interfaceByNameReturns = struct {
		result1 *net.Interface
		result2 error
	}{result1, result2}
}

func (fake *NetAdapter) InterfaceByNameReturnsOnCall(i int, result1 *net.Interface, result2 error) {
	fake.interfaceByNameMutex.Lock()
	defer fake.interfaceByNameMutex.Unlock()
	fake.InterfaceByNameStub = nil
	if fake.interfaceByNameReturnsOnCall == nil {
		fake.interfaceByNameReturnsOnCall = make(map[int]struct {
			result1 *net.Interface
			result2 error
		})
	}
	fake.interfaceByNameReturnsOnCall[i] = struct {
		result1 *net.Interface
		result2 error
	}{result1, result2}
}

func (fake *NetAdapter) Interfaces() ([]net.Interface, error) {
	fake.interfacesMutex.Lock()
	ret, specificReturn := fake.interfacesReturnsOnCall[len(fake.interfacesArgsForCall)]
	fake.interfacesArgsForCall = append(fake.interfacesArgsForCall, struct {
	}{})
	stub := fake.InterfacesStub
	fakeReturns := fake.interfacesReturns
	fake.recordInvocation("Interfaces", []interface{}{})
	fake.interfacesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *NetAdapter) InterfacesCallCount() int {
	fake.interfacesMutex.RLock()
	defer fake.interfacesMutex.RUnlock()
	return len(fake.interfacesArgsForCall)
}

func (fake *NetAdapter) InterfacesCalls(stub func() ([]net.Interface, error)) {
	fake.interfacesMutex.Lock()
	defer fake.interfacesMutex.Unlock()
	fake.InterfacesStub = stub
}

func (fake *NetAdapter) InterfacesReturns(result1 []net.Interface, result2 error) {
	fake.interfacesMutex.Lock()
	defer fake.interfacesMutex.Unlock()
	fake.InterfacesStub = nil
	fake.interfacesReturns = struct {
		result1 []net.Interface
		result2 error
	}{result1, result2}
}

func (fake *NetAdapter) InterfacesReturnsOnCall(i int, result1 []net.Interface, result2 error) {
	fake.interfacesMutex.Lock()
	defer fake.interfacesMutex.Unlock()
	fake.InterfacesStub = nil
	if fake.interfacesReturnsOnCall == nil {
		fake.interfacesReturnsOnCall = make(map[int]struct {
			result1 []net.Interface
			result2 error
		})
	}
	fake.interfacesReturnsOnCall[i] = struct {
		result1 []net.Interface
		result2 error
	}{result1, result2}
}

func (fake *NetAdapter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.interfaceAddrsMutex.RLock()
	defer fake.interfaceAddrsMutex.RUnlock()
	fake.interfaceByNameMutex.RLock()
	defer fake.interfaceByNameMutex.RUnlock()
	fake.interfacesMutex.RLock()
	defer fake.interfacesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *NetAdapter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
