// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/policy_client"
)

type PolicyClient struct {
	CreateOrGetTagStub        func(string, string) (string, error)
	createOrGetTagMutex       sync.RWMutex
	createOrGetTagArgsForCall []struct {
		arg1 string
		arg2 string
	}
	createOrGetTagReturns struct {
		result1 string
		result2 error
	}
	createOrGetTagReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetPoliciesByIDStub        func(...string) ([]policy_client.Policy, []policy_client.EgressPolicy, error)
	getPoliciesByIDMutex       sync.RWMutex
	getPoliciesByIDArgsForCall []struct {
		arg1 []string
	}
	getPoliciesByIDReturns struct {
		result1 []policy_client.Policy
		result2 []policy_client.EgressPolicy
		result3 error
	}
	getPoliciesByIDReturnsOnCall map[int]struct {
		result1 []policy_client.Policy
		result2 []policy_client.EgressPolicy
		result3 error
	}
	GetSecurityGroupsForSpaceStub        func(...string) ([]policy_client.SecurityGroup, error)
	getSecurityGroupsForSpaceMutex       sync.RWMutex
	getSecurityGroupsForSpaceArgsForCall []struct {
		arg1 []string
	}
	getSecurityGroupsForSpaceReturns struct {
		result1 []policy_client.SecurityGroup
		result2 error
	}
	getSecurityGroupsForSpaceReturnsOnCall map[int]struct {
		result1 []policy_client.SecurityGroup
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PolicyClient) CreateOrGetTag(arg1 string, arg2 string) (string, error) {
	fake.createOrGetTagMutex.Lock()
	ret, specificReturn := fake.createOrGetTagReturnsOnCall[len(fake.createOrGetTagArgsForCall)]
	fake.createOrGetTagArgsForCall = append(fake.createOrGetTagArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.CreateOrGetTagStub
	fakeReturns := fake.createOrGetTagReturns
	fake.recordInvocation("CreateOrGetTag", []interface{}{arg1, arg2})
	fake.createOrGetTagMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PolicyClient) CreateOrGetTagCallCount() int {
	fake.createOrGetTagMutex.RLock()
	defer fake.createOrGetTagMutex.RUnlock()
	return len(fake.createOrGetTagArgsForCall)
}

func (fake *PolicyClient) CreateOrGetTagCalls(stub func(string, string) (string, error)) {
	fake.createOrGetTagMutex.Lock()
	defer fake.createOrGetTagMutex.Unlock()
	fake.CreateOrGetTagStub = stub
}

func (fake *PolicyClient) CreateOrGetTagArgsForCall(i int) (string, string) {
	fake.createOrGetTagMutex.RLock()
	defer fake.createOrGetTagMutex.RUnlock()
	argsForCall := fake.createOrGetTagArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PolicyClient) CreateOrGetTagReturns(result1 string, result2 error) {
	fake.createOrGetTagMutex.Lock()
	defer fake.createOrGetTagMutex.Unlock()
	fake.CreateOrGetTagStub = nil
	fake.createOrGetTagReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *PolicyClient) CreateOrGetTagReturnsOnCall(i int, result1 string, result2 error) {
	fake.createOrGetTagMutex.Lock()
	defer fake.createOrGetTagMutex.Unlock()
	fake.CreateOrGetTagStub = nil
	if fake.createOrGetTagReturnsOnCall == nil {
		fake.createOrGetTagReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.createOrGetTagReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *PolicyClient) GetPoliciesByID(arg1 ...string) ([]policy_client.Policy, []policy_client.EgressPolicy, error) {
	fake.getPoliciesByIDMutex.Lock()
	ret, specificReturn := fake.getPoliciesByIDReturnsOnCall[len(fake.getPoliciesByIDArgsForCall)]
	fake.getPoliciesByIDArgsForCall = append(fake.getPoliciesByIDArgsForCall, struct {
		arg1 []string
	}{arg1})
	stub := fake.GetPoliciesByIDStub
	fakeReturns := fake.getPoliciesByIDReturns
	fake.recordInvocation("GetPoliciesByID", []interface{}{arg1})
	fake.getPoliciesByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1...)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *PolicyClient) GetPoliciesByIDCallCount() int {
	fake.getPoliciesByIDMutex.RLock()
	defer fake.getPoliciesByIDMutex.RUnlock()
	return len(fake.getPoliciesByIDArgsForCall)
}

func (fake *PolicyClient) GetPoliciesByIDCalls(stub func(...string) ([]policy_client.Policy, []policy_client.EgressPolicy, error)) {
	fake.getPoliciesByIDMutex.Lock()
	defer fake.getPoliciesByIDMutex.Unlock()
	fake.GetPoliciesByIDStub = stub
}

func (fake *PolicyClient) GetPoliciesByIDArgsForCall(i int) []string {
	fake.getPoliciesByIDMutex.RLock()
	defer fake.getPoliciesByIDMutex.RUnlock()
	argsForCall := fake.getPoliciesByIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *PolicyClient) GetPoliciesByIDReturns(result1 []policy_client.Policy, result2 []policy_client.EgressPolicy, result3 error) {
	fake.getPoliciesByIDMutex.Lock()
	defer fake.getPoliciesByIDMutex.Unlock()
	fake.GetPoliciesByIDStub = nil
	fake.getPoliciesByIDReturns = struct {
		result1 []policy_client.Policy
		result2 []policy_client.EgressPolicy
		result3 error
	}{result1, result2, result3}
}

func (fake *PolicyClient) GetPoliciesByIDReturnsOnCall(i int, result1 []policy_client.Policy, result2 []policy_client.EgressPolicy, result3 error) {
	fake.getPoliciesByIDMutex.Lock()
	defer fake.getPoliciesByIDMutex.Unlock()
	fake.GetPoliciesByIDStub = nil
	if fake.getPoliciesByIDReturnsOnCall == nil {
		fake.getPoliciesByIDReturnsOnCall = make(map[int]struct {
			result1 []policy_client.Policy
			result2 []policy_client.EgressPolicy
			result3 error
		})
	}
	fake.getPoliciesByIDReturnsOnCall[i] = struct {
		result1 []policy_client.Policy
		result2 []policy_client.EgressPolicy
		result3 error
	}{result1, result2, result3}
}

func (fake *PolicyClient) GetSecurityGroupsForSpace(arg1 ...string) ([]policy_client.SecurityGroup, error) {
	fake.getSecurityGroupsForSpaceMutex.Lock()
	ret, specificReturn := fake.getSecurityGroupsForSpaceReturnsOnCall[len(fake.getSecurityGroupsForSpaceArgsForCall)]
	fake.getSecurityGroupsForSpaceArgsForCall = append(fake.getSecurityGroupsForSpaceArgsForCall, struct {
		arg1 []string
	}{arg1})
	stub := fake.GetSecurityGroupsForSpaceStub
	fakeReturns := fake.getSecurityGroupsForSpaceReturns
	fake.recordInvocation("GetSecurityGroupsForSpace", []interface{}{arg1})
	fake.getSecurityGroupsForSpaceMutex.Unlock()
	if stub != nil {
		return stub(arg1...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PolicyClient) GetSecurityGroupsForSpaceCallCount() int {
	fake.getSecurityGroupsForSpaceMutex.RLock()
	defer fake.getSecurityGroupsForSpaceMutex.RUnlock()
	return len(fake.getSecurityGroupsForSpaceArgsForCall)
}

func (fake *PolicyClient) GetSecurityGroupsForSpaceCalls(stub func(...string) ([]policy_client.SecurityGroup, error)) {
	fake.getSecurityGroupsForSpaceMutex.Lock()
	defer fake.getSecurityGroupsForSpaceMutex.Unlock()
	fake.GetSecurityGroupsForSpaceStub = stub
}

func (fake *PolicyClient) GetSecurityGroupsForSpaceArgsForCall(i int) []string {
	fake.getSecurityGroupsForSpaceMutex.RLock()
	defer fake.getSecurityGroupsForSpaceMutex.RUnlock()
	argsForCall := fake.getSecurityGroupsForSpaceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *PolicyClient) GetSecurityGroupsForSpaceReturns(result1 []policy_client.SecurityGroup, result2 error) {
	fake.getSecurityGroupsForSpaceMutex.Lock()
	defer fake.getSecurityGroupsForSpaceMutex.Unlock()
	fake.GetSecurityGroupsForSpaceStub = nil
	fake.getSecurityGroupsForSpaceReturns = struct {
		result1 []policy_client.SecurityGroup
		result2 error
	}{result1, result2}
}

func (fake *PolicyClient) GetSecurityGroupsForSpaceReturnsOnCall(i int, result1 []policy_client.SecurityGroup, result2 error) {
	fake.getSecurityGroupsForSpaceMutex.Lock()
	defer fake.getSecurityGroupsForSpaceMutex.Unlock()
	fake.GetSecurityGroupsForSpaceStub = nil
	if fake.getSecurityGroupsForSpaceReturnsOnCall == nil {
		fake.getSecurityGroupsForSpaceReturnsOnCall = make(map[int]struct {
			result1 []policy_client.SecurityGroup
			result2 error
		})
	}
	fake.getSecurityGroupsForSpaceReturnsOnCall[i] = struct {
		result1 []policy_client.SecurityGroup
		result2 error
	}{result1, result2}
}

func (fake *PolicyClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createOrGetTagMutex.RLock()
	defer fake.createOrGetTagMutex.RUnlock()
	fake.getPoliciesByIDMutex.RLock()
	defer fake.getPoliciesByIDMutex.RUnlock()
	fake.getSecurityGroupsForSpaceMutex.RLock()
	defer fake.getSecurityGroupsForSpaceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PolicyClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
