// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/netmon/network_stats_fetcher"
)

type NetworkStatsFetcher struct {
	CountIPTablesRulesStub        func() (int, error)
	countIPTablesRulesMutex       sync.RWMutex
	countIPTablesRulesArgsForCall []struct {
	}
	countIPTablesRulesReturns struct {
		result1 int
		result2 error
	}
	countIPTablesRulesReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *NetworkStatsFetcher) CountIPTablesRules() (int, error) {
	fake.countIPTablesRulesMutex.Lock()
	ret, specificReturn := fake.countIPTablesRulesReturnsOnCall[len(fake.countIPTablesRulesArgsForCall)]
	fake.countIPTablesRulesArgsForCall = append(fake.countIPTablesRulesArgsForCall, struct {
	}{})
	stub := fake.CountIPTablesRulesStub
	fakeReturns := fake.countIPTablesRulesReturns
	fake.recordInvocation("CountIPTablesRules", []interface{}{})
	fake.countIPTablesRulesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *NetworkStatsFetcher) CountIPTablesRulesCallCount() int {
	fake.countIPTablesRulesMutex.RLock()
	defer fake.countIPTablesRulesMutex.RUnlock()
	return len(fake.countIPTablesRulesArgsForCall)
}

func (fake *NetworkStatsFetcher) CountIPTablesRulesCalls(stub func() (int, error)) {
	fake.countIPTablesRulesMutex.Lock()
	defer fake.countIPTablesRulesMutex.Unlock()
	fake.CountIPTablesRulesStub = stub
}

func (fake *NetworkStatsFetcher) CountIPTablesRulesReturns(result1 int, result2 error) {
	fake.countIPTablesRulesMutex.Lock()
	defer fake.countIPTablesRulesMutex.Unlock()
	fake.CountIPTablesRulesStub = nil
	fake.countIPTablesRulesReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *NetworkStatsFetcher) CountIPTablesRulesReturnsOnCall(i int, result1 int, result2 error) {
	fake.countIPTablesRulesMutex.Lock()
	defer fake.countIPTablesRulesMutex.Unlock()
	fake.CountIPTablesRulesStub = nil
	if fake.countIPTablesRulesReturnsOnCall == nil {
		fake.countIPTablesRulesReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.countIPTablesRulesReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *NetworkStatsFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.countIPTablesRulesMutex.RLock()
	defer fake.countIPTablesRulesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *NetworkStatsFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ network_stats_fetcher.NetworkStatsFetcher = new(NetworkStatsFetcher)
