#!/bin/bash

set -e
set -o pipefail

if (( $# != 1 )); then
  echo "missing concourse target"
  echo ""
  echo "example usage:"
  echo "fly-execute my-target"
  exit 1
fi

export DB=${DB:-"postgres"} # if not set, default to postgres

DIR=$(cd $(dirname $0)/.. && pwd)
fly -t $1 execute \
  --privileged \
  --input release=${DIR} \
  --config ../tas-runtime/ci/tasks/cf-networking/${DB}-tests/task.yml
