#!/bin/bash

set -e

function sync_package() {
  bosh_pkg=${1}

  shift

  (
    set -e


    cd src/code.cloudfoundry.org

    spec=../../packages/${bosh_pkg}/spec

    {
      cat $spec | grep -v "# gosub-main-module"

      for package in $(gosub list "$@"); do
        repo=$(echo ${2} | cut -f1-3 -d/)
        if [ -d "../../src/code.cloudfoundry.org/vendor/${package}" ]; then
          package="code.cloudfoundry.org/vendor/${package}"
        fi
        echo ${package} | sed -e 's/\(.*\)/  - \1\/*.go # gosub-main-module/g'
        if ls ../../src/${package}/*.s >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/*.s # gosub-main-module/g'
        fi
        if ls ../../src/${package}/*.h >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/*.h # gosub-main-module/g'
        fi
      done
    } > $spec.new

    mv $spec.new $spec
  )
}

function sync_package_externalmods() {
  bosh_pkg=${1}

  shift 1

  (
    set -e


    cd src/code.cloudfoundry.org/externalmods

    spec=../../../packages/${bosh_pkg}/spec

    {
      cat $spec | grep -v "# gosub-externalmods"

      for package in $(gosub list "$@"); do
        repo=$(echo ${2} | cut -f1-3 -d/)
        if [ ! -d "${package/code.cloudfoundry.org\/externalmods/.}" ]; then
          package="code.cloudfoundry.org/externalmods/vendor/${package}"
        fi
        echo ${package} | sed -e 's/\(.*\)/  - \1\/*.go # gosub-externalmods/g'
        if ls ${package/code.cloudfoundry.org\/externalmods/.}/*.s >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/*.s # gosub-externalmods/g'
        fi
        if ls ${package/code.cloudfoundry.org\/externalmods/.}/*.h >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/*.h # gosub-externalmods/g'
        fi
      done
    } > $spec.new

    mv $spec.new $spec
  )
}

## Create a sync_package line for each BOSH package in this release
## add a -app line or -test line to include a particular app or test
## along with all of its dependencies

sync_package vxlan-policy-agent \
  -app code.cloudfoundry.org/vxlan-policy-agent/cmd/vxlan-policy-agent \
  -app code.cloudfoundry.org/vxlan-policy-agent/cmd/pre-start


sync_package netmon \
  -app code.cloudfoundry.org/netmon/cmd/netmon

sync_package silk-controller \
  -app code.cloudfoundry.org/silk/cmd/silk-controller

sync_package silk-daemon \
  -app code.cloudfoundry.org/silk/cmd/silk-daemon \
  -app code.cloudfoundry.org/silk/cmd/silk-teardown \
  -app code.cloudfoundry.org/silk-daemon-shutdown \
  -app code.cloudfoundry.org/silk-daemon-bootstrap

GOOS=linux sync_package silk-cni \
  -app code.cloudfoundry.org/silk/cmd/silk-cni \
  -app code.cloudfoundry.org/cni-wrapper-plugin \
  -app code.cloudfoundry.org/cni-teardown

GOOS=linux sync_package_externalmods silk-cni \
  -app github.com/containernetworking/plugins/plugins/ipam/host-local \
  -app github.com/containernetworking/plugins/plugins/meta/bandwidth

GOOS=linux sync_package iptables-logger \
  -app code.cloudfoundry.org/iptables-logger/cmd/iptables-logger

git diff --name-only packages/*/spec
