#!/bin/bash
set -e -x

if ! which gosub >/dev/null 2>&1 ; then
  echo "gosub not found. In the global $GOPATH, try: go get github.com/vito/gosub"
  exit 1
fi

ROOT_DIR_PATH=$(cd "$(dirname "$0")"/.. && pwd)
GOPATH=$ROOT_DIR_PATH

function sync_package() {
  bosh_pkg=${1}

  shift

  (
    set -e

    cd packages/${bosh_pkg}

    {
      cat spec | grep -v '# gosub'

      for package in $(gosub list "$@"); do
        repo=$(echo ${2} | cut -f1-3 -d/)
        if [ -d "../../src/${repo}/Godeps/_workspace/src/${package}" ]; then
          package="${repo}/Godeps/_workspace/src/${package}"
        fi
        echo ${package} | sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
        if ls ../../src/${package}/*.s >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/*.s # gosub/g'
        fi
        if ls ../../src/${package}/**/*.c >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/**\/*.c # gosub/g'
        fi
        if ls ../../src/${package}/**/*.h >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/**\/*.h # gosub/g'
        fi
      done
    } > spec.new

    mv spec.new spec
  )
}

sync_package vxlan-policy-agent-windows \
  -app vxlan-policy-agent/cmd/vxlan-policy-agent-windows
