// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"
)

type MetricSender struct {
	IncrementCounterStub        func(string)
	incrementCounterMutex       sync.RWMutex
	incrementCounterArgsForCall []struct {
		arg1 string
	}
	SendValueStub        func(string, float64, string)
	sendValueMutex       sync.RWMutex
	sendValueArgsForCall []struct {
		arg1 string
		arg2 float64
		arg3 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *MetricSender) IncrementCounter(arg1 string) {
	fake.incrementCounterMutex.Lock()
	fake.incrementCounterArgsForCall = append(fake.incrementCounterArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncrementCounterStub
	fake.recordInvocation("IncrementCounter", []interface{}{arg1})
	fake.incrementCounterMutex.Unlock()
	if stub != nil {
		fake.IncrementCounterStub(arg1)
	}
}

func (fake *MetricSender) IncrementCounterCallCount() int {
	fake.incrementCounterMutex.RLock()
	defer fake.incrementCounterMutex.RUnlock()
	return len(fake.incrementCounterArgsForCall)
}

func (fake *MetricSender) IncrementCounterCalls(stub func(string)) {
	fake.incrementCounterMutex.Lock()
	defer fake.incrementCounterMutex.Unlock()
	fake.IncrementCounterStub = stub
}

func (fake *MetricSender) IncrementCounterArgsForCall(i int) string {
	fake.incrementCounterMutex.RLock()
	defer fake.incrementCounterMutex.RUnlock()
	argsForCall := fake.incrementCounterArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MetricSender) SendValue(arg1 string, arg2 float64, arg3 string) {
	fake.sendValueMutex.Lock()
	fake.sendValueArgsForCall = append(fake.sendValueArgsForCall, struct {
		arg1 string
		arg2 float64
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.SendValueStub
	fake.recordInvocation("SendValue", []interface{}{arg1, arg2, arg3})
	fake.sendValueMutex.Unlock()
	if stub != nil {
		fake.SendValueStub(arg1, arg2, arg3)
	}
}

func (fake *MetricSender) SendValueCallCount() int {
	fake.sendValueMutex.RLock()
	defer fake.sendValueMutex.RUnlock()
	return len(fake.sendValueArgsForCall)
}

func (fake *MetricSender) SendValueCalls(stub func(string, float64, string)) {
	fake.sendValueMutex.Lock()
	defer fake.sendValueMutex.Unlock()
	fake.SendValueStub = stub
}

func (fake *MetricSender) SendValueArgsForCall(i int) (string, float64, string) {
	fake.sendValueMutex.RLock()
	defer fake.sendValueMutex.RUnlock()
	argsForCall := fake.sendValueArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *MetricSender) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.incrementCounterMutex.RLock()
	defer fake.incrementCounterMutex.RUnlock()
	fake.sendValueMutex.RLock()
	defer fake.sendValueMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *MetricSender) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
