// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/silk/controller"
)

type LeaseAcquirer struct {
	AcquireSubnetLeaseStub        func(string, bool) (*controller.Lease, error)
	acquireSubnetLeaseMutex       sync.RWMutex
	acquireSubnetLeaseArgsForCall []struct {
		arg1 string
		arg2 bool
	}
	acquireSubnetLeaseReturns struct {
		result1 *controller.Lease
		result2 error
	}
	acquireSubnetLeaseReturnsOnCall map[int]struct {
		result1 *controller.Lease
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *LeaseAcquirer) AcquireSubnetLease(arg1 string, arg2 bool) (*controller.Lease, error) {
	fake.acquireSubnetLeaseMutex.Lock()
	ret, specificReturn := fake.acquireSubnetLeaseReturnsOnCall[len(fake.acquireSubnetLeaseArgsForCall)]
	fake.acquireSubnetLeaseArgsForCall = append(fake.acquireSubnetLeaseArgsForCall, struct {
		arg1 string
		arg2 bool
	}{arg1, arg2})
	stub := fake.AcquireSubnetLeaseStub
	fakeReturns := fake.acquireSubnetLeaseReturns
	fake.recordInvocation("AcquireSubnetLease", []interface{}{arg1, arg2})
	fake.acquireSubnetLeaseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *LeaseAcquirer) AcquireSubnetLeaseCallCount() int {
	fake.acquireSubnetLeaseMutex.RLock()
	defer fake.acquireSubnetLeaseMutex.RUnlock()
	return len(fake.acquireSubnetLeaseArgsForCall)
}

func (fake *LeaseAcquirer) AcquireSubnetLeaseCalls(stub func(string, bool) (*controller.Lease, error)) {
	fake.acquireSubnetLeaseMutex.Lock()
	defer fake.acquireSubnetLeaseMutex.Unlock()
	fake.AcquireSubnetLeaseStub = stub
}

func (fake *LeaseAcquirer) AcquireSubnetLeaseArgsForCall(i int) (string, bool) {
	fake.acquireSubnetLeaseMutex.RLock()
	defer fake.acquireSubnetLeaseMutex.RUnlock()
	argsForCall := fake.acquireSubnetLeaseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *LeaseAcquirer) AcquireSubnetLeaseReturns(result1 *controller.Lease, result2 error) {
	fake.acquireSubnetLeaseMutex.Lock()
	defer fake.acquireSubnetLeaseMutex.Unlock()
	fake.AcquireSubnetLeaseStub = nil
	fake.acquireSubnetLeaseReturns = struct {
		result1 *controller.Lease
		result2 error
	}{result1, result2}
}

func (fake *LeaseAcquirer) AcquireSubnetLeaseReturnsOnCall(i int, result1 *controller.Lease, result2 error) {
	fake.acquireSubnetLeaseMutex.Lock()
	defer fake.acquireSubnetLeaseMutex.Unlock()
	fake.AcquireSubnetLeaseStub = nil
	if fake.acquireSubnetLeaseReturnsOnCall == nil {
		fake.acquireSubnetLeaseReturnsOnCall = make(map[int]struct {
			result1 *controller.Lease
			result2 error
		})
	}
	fake.acquireSubnetLeaseReturnsOnCall[i] = struct {
		result1 *controller.Lease
		result2 error
	}{result1, result2}
}

func (fake *LeaseAcquirer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.acquireSubnetLeaseMutex.RLock()
	defer fake.acquireSubnetLeaseMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *LeaseAcquirer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
