// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/iptables-logger/parser"
)

type KernelLogParser struct {
	IsIPTablesLogDataStub        func(string) bool
	isIPTablesLogDataMutex       sync.RWMutex
	isIPTablesLogDataArgsForCall []struct {
		arg1 string
	}
	isIPTablesLogDataReturns struct {
		result1 bool
	}
	isIPTablesLogDataReturnsOnCall map[int]struct {
		result1 bool
	}
	ParseStub        func(string) parser.ParsedData
	parseMutex       sync.RWMutex
	parseArgsForCall []struct {
		arg1 string
	}
	parseReturns struct {
		result1 parser.ParsedData
	}
	parseReturnsOnCall map[int]struct {
		result1 parser.ParsedData
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *KernelLogParser) IsIPTablesLogData(arg1 string) bool {
	fake.isIPTablesLogDataMutex.Lock()
	ret, specificReturn := fake.isIPTablesLogDataReturnsOnCall[len(fake.isIPTablesLogDataArgsForCall)]
	fake.isIPTablesLogDataArgsForCall = append(fake.isIPTablesLogDataArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IsIPTablesLogDataStub
	fakeReturns := fake.isIPTablesLogDataReturns
	fake.recordInvocation("IsIPTablesLogData", []interface{}{arg1})
	fake.isIPTablesLogDataMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KernelLogParser) IsIPTablesLogDataCallCount() int {
	fake.isIPTablesLogDataMutex.RLock()
	defer fake.isIPTablesLogDataMutex.RUnlock()
	return len(fake.isIPTablesLogDataArgsForCall)
}

func (fake *KernelLogParser) IsIPTablesLogDataCalls(stub func(string) bool) {
	fake.isIPTablesLogDataMutex.Lock()
	defer fake.isIPTablesLogDataMutex.Unlock()
	fake.IsIPTablesLogDataStub = stub
}

func (fake *KernelLogParser) IsIPTablesLogDataArgsForCall(i int) string {
	fake.isIPTablesLogDataMutex.RLock()
	defer fake.isIPTablesLogDataMutex.RUnlock()
	argsForCall := fake.isIPTablesLogDataArgsForCall[i]
	return argsForCall.arg1
}

func (fake *KernelLogParser) IsIPTablesLogDataReturns(result1 bool) {
	fake.isIPTablesLogDataMutex.Lock()
	defer fake.isIPTablesLogDataMutex.Unlock()
	fake.IsIPTablesLogDataStub = nil
	fake.isIPTablesLogDataReturns = struct {
		result1 bool
	}{result1}
}

func (fake *KernelLogParser) IsIPTablesLogDataReturnsOnCall(i int, result1 bool) {
	fake.isIPTablesLogDataMutex.Lock()
	defer fake.isIPTablesLogDataMutex.Unlock()
	fake.IsIPTablesLogDataStub = nil
	if fake.isIPTablesLogDataReturnsOnCall == nil {
		fake.isIPTablesLogDataReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isIPTablesLogDataReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *KernelLogParser) Parse(arg1 string) parser.ParsedData {
	fake.parseMutex.Lock()
	ret, specificReturn := fake.parseReturnsOnCall[len(fake.parseArgsForCall)]
	fake.parseArgsForCall = append(fake.parseArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ParseStub
	fakeReturns := fake.parseReturns
	fake.recordInvocation("Parse", []interface{}{arg1})
	fake.parseMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KernelLogParser) ParseCallCount() int {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return len(fake.parseArgsForCall)
}

func (fake *KernelLogParser) ParseCalls(stub func(string) parser.ParsedData) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = stub
}

func (fake *KernelLogParser) ParseArgsForCall(i int) string {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	argsForCall := fake.parseArgsForCall[i]
	return argsForCall.arg1
}

func (fake *KernelLogParser) ParseReturns(result1 parser.ParsedData) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = nil
	fake.parseReturns = struct {
		result1 parser.ParsedData
	}{result1}
}

func (fake *KernelLogParser) ParseReturnsOnCall(i int, result1 parser.ParsedData) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = nil
	if fake.parseReturnsOnCall == nil {
		fake.parseReturnsOnCall = make(map[int]struct {
			result1 parser.ParsedData
		})
	}
	fake.parseReturnsOnCall[i] = struct {
		result1 parser.ParsedData
	}{result1}
}

func (fake *KernelLogParser) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.isIPTablesLogDataMutex.RLock()
	defer fake.isIPTablesLogDataMutex.RUnlock()
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *KernelLogParser) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
