---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/dev-mysql

inputs:
  - name: silk

run:
  path: /bin/bash
  args:
    - -c
    - |
      cd silk
      export DB=mysql
      scripts/test.sh
